num_iters: 10000000
batch_size: 64
critic_steps: 5
d_dim: 256
d_lr: 0.0002
g_lr: 0.0004
inv_lr: 0.0002
num_points_per_object: 1000
optimizer: rmsprop
type: approxfisher
x_dim: 3
z1_dim: 256
z2_dim: 10
weight_clip: 0.2
add_noise: False
kernel: l2
data_file: /home/chunlial/ModelNet40_cloud.h5
obj: multi40
base: 1.0
pool: max1
lambda_grad_pen: 0.05
arc: MLP
invact: tanh
ro: False
n_obj: 10000
o_dim: 1
